//! CLI command modules.

pub mod agent;
#[cfg(feature = "auth")]
pub mod auth;
pub mod channel;
#[cfg(feature = "cluster")]
pub mod cluster;
pub mod cors;
pub mod cron;
pub mod dashboard;
pub mod estop;
#[cfg(feature = "forge")]
pub mod forge;
pub mod gateway;
pub mod log;
pub mod mcp;
#[cfg(feature = "memory")]
pub mod memory;
#[cfg(feature = "migrate")]
pub mod migrate;
pub mod model;
pub mod persona;
#[cfg(feature = "sandbox")]
pub mod sandbox;
#[cfg(feature = "security")]
pub mod scanner;
#[cfg(feature = "security")]
pub mod security;
pub mod shutdown;
pub mod skills;
pub mod status;
#[cfg(feature = "desktop")]
pub mod test_cmd;
#[cfg(feature = "voice")]
pub mod voice;
#[cfg(feature = "workflow")]
pub mod workflow;
