//! CLI command modules.

pub mod gateway;
#[cfg(feature = "cluster")]
pub mod cluster;
pub mod model;
pub mod forge;
pub mod security;
pub mod skills;
pub mod workflow;
pub mod scanner;
pub mod memory;
pub mod log;
pub mod agent;
#[cfg(feature = "auth")]
pub mod auth;
pub mod channel;
pub mod cron;
pub mod dashboard;
pub mod mcp;
pub mod status;
pub mod shutdown;
pub mod cors;
#[cfg(feature = "migrate")]
pub mod migrate;
#[cfg(feature = "voice")]
pub mod voice;
pub mod persona;
#[cfg(feature = "desktop")]
pub mod test_cmd;
