discovered = []
last_sync = "2026-06-13T17:40:38.687042200+08:00"

[cluster]
id = "auto-discovered"
auto_discovery = true
last_updated = "2026-06-13T17:40:38.687041400+08:00"
rpc_auth_token = ""

[local_node]
id = "local-node-001"
name = "Bot local-no"
address = "127.0.0.1:9000"
role = "worker"
category = "general"
tags = []
capabilities = []
