//! The `.config` selection file — the developer's current on/off choices.
//!
//! Stored at `scripts/customize/.config`. Absence of this file means "no
//! customization" = full default build (see export.rs and the bridge scripts).

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BuildConfig {
    /// Boolean feature toggles (id -> on/off).
    #[serde(default)]
    pub features: BTreeMap<String, bool>,
    /// Enum feature selections (id -> chosen option), e.g. build-profile.
    #[serde(default)]
    pub enums: BTreeMap<String, String>,
}

impl BuildConfig {
    pub fn parse(text: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(text)
    }

    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("read config {}: {}", path.display(), e))?;
        Self::parse(&text).map_err(|e| anyhow::anyhow!("parse config {}: {}", path.display(), e))
    }

    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let mut body = String::from(
            "# NemesisBot build configuration (generated by nemesis-config).\n\
             # Remove this file to return to the full default build.\n\n",
        );
        let me =
            toml::to_string_pretty(self).map_err(|e| anyhow::anyhow!("serialize config: {}", e))?;
        body.push_str(&me);
        std::fs::write(path, body)
            .map_err(|e| anyhow::anyhow!("write config {}: {}", path.display(), e))
    }

    pub fn set_bool(&mut self, id: &str, on: bool) {
        self.features.insert(id.to_string(), on);
    }

    pub fn get_bool(&self, id: &str) -> Option<bool> {
        self.features.get(id).copied()
    }

    pub fn set_enum(&mut self, id: &str, value: &str) {
        self.enums.insert(id.to_string(), value.to_string());
    }

    pub fn get_enum(&self, id: &str) -> Option<&str> {
        self.enums.get(id).map(|s| s.as_str())
    }

    /// Build a config from a manifest by applying each feature's `default`.
    pub fn from_defaults(manifest: &crate::manifest::FeatureManifest) -> Self {
        let mut cfg = Self::default();
        for f in &manifest.features {
            if f.is_enum() {
                if let Some(v) = f.default.as_str() {
                    cfg.set_enum(&f.id, v);
                }
            } else {
                cfg.set_bool(&f.id, f.default.as_bool().unwrap_or(false));
            }
        }
        cfg
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_and_access() {
        let text = r#"
[features]
channels-web = true
migrate = false

[enums]
build-profile = "iotsmall"
"#;
        let cfg = BuildConfig::parse(text).unwrap();
        assert_eq!(cfg.get_bool("channels-web"), Some(true));
        assert_eq!(cfg.get_bool("migrate"), Some(false));
        assert_eq!(cfg.get_enum("build-profile"), Some("iotsmall"));
        assert_eq!(cfg.get_bool("nonexistent"), None);
    }

    #[test]
    fn toggle_and_serialize_roundtrip() {
        let mut cfg = BuildConfig::default();
        cfg.set_bool("channels-web", true);
        cfg.set_bool("channels-rpc", true);
        cfg.set_enum("build-profile", "release");
        let text = toml::to_string_pretty(&cfg).unwrap();
        let cfg2 = BuildConfig::parse(&text).unwrap();
        assert_eq!(cfg2.get_bool("channels-web"), Some(true));
        assert_eq!(cfg2.get_bool("channels-rpc"), Some(true));
        assert_eq!(cfg2.get_enum("build-profile"), Some("release"));
    }

    #[test]
    fn from_defaults_uses_manifest_defaults() {
        let m = crate::manifest::FeatureManifest::parse(
            r#"
[[feature]]
id = "a"
default = true
[[feature]]
id = "b"
default = false
[[feature]]
id = "build-profile"
type = "enum"
default = "iotsmall"
"#,
        )
        .unwrap();
        let cfg = BuildConfig::from_defaults(&m);
        assert_eq!(cfg.get_bool("a"), Some(true));
        assert_eq!(cfg.get_bool("b"), Some(false));
        assert_eq!(cfg.get_enum("build-profile"), Some("iotsmall"));
    }
}
