//! The `.config` selection file — the developer's current on/off choices.
//!
//! Stored at `scripts/customize/.config`. Absence of this file means "no
//! customization" = full default build (see export.rs and the bridge scripts).

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BuildConfig {
    /// Boolean feature toggles (id -> on/off).
    #[serde(default)]
    pub features: BTreeMap<String, bool>,
    /// Enum feature selections (id -> chosen option), e.g. build-profile.
    #[serde(default)]
    pub enums: BTreeMap<String, String>,
}

impl BuildConfig {
    pub fn parse(text: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(text)
    }

    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("read config {}: {}", path.display(), e))?;
        Self::parse(&text).map_err(|e| anyhow::anyhow!("parse config {}: {}", path.display(), e))
    }

    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let mut body = String::from(
            "# NemesisBot build configuration (generated by nemesis-config).\n\
             # Remove this file to return to the full default build.\n\n",
        );
        let me =
            toml::to_string_pretty(self).map_err(|e| anyhow::anyhow!("serialize config: {}", e))?;
        body.push_str(&me);
        std::fs::write(path, body)
            .map_err(|e| anyhow::anyhow!("write config {}: {}", path.display(), e))
    }

    pub fn set_bool(&mut self, id: &str, on: bool) {
        self.features.insert(id.to_string(), on);
    }

    pub fn get_bool(&self, id: &str) -> Option<bool> {
        self.features.get(id).copied()
    }

    pub fn set_enum(&mut self, id: &str, value: &str) {
        self.enums.insert(id.to_string(), value.to_string());
    }

    pub fn get_enum(&self, id: &str) -> Option<&str> {
        self.enums.get(id).map(|s| s.as_str())
    }

    /// Build a config from a manifest by applying each feature's `default`.
    pub fn from_defaults(manifest: &crate::manifest::FeatureManifest) -> Self {
        let mut cfg = Self::default();
        for f in &manifest.features {
            if f.is_enum() {
                if let Some(v) = f.default.as_str() {
                    cfg.set_enum(&f.id, v);
                }
            } else {
                cfg.set_bool(&f.id, f.default.as_bool().unwrap_or(false));
            }
        }
        cfg
    }
}

#[cfg(test)]
mod tests;
#[cfg(test)]
mod w5d_tests;
