//! The feature manifest (`features.toml`) — the single source of truth for
//! what the configurator can toggle. Authored by hand (descriptions/grouping)
//! and/or scaffolded by `init` from the real `[features]` in Cargo.toml.

use std::collections::BTreeSet;
use std::path::Path;

use serde::{Deserialize, Serialize};

/// A `default` value is either a boolean (for on/off features) or a string
/// (for enum features such as `build-profile`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DefaultVal {
    Bool(bool),
    Str(String),
}

impl Default for DefaultVal {
    fn default() -> Self {
        DefaultVal::Bool(false)
    }
}

impl DefaultVal {
    pub fn as_bool(&self) -> Option<bool> {
        match self {
            DefaultVal::Bool(b) => Some(*b),
            DefaultVal::Str(_) => None,
        }
    }
    pub fn as_str(&self) -> Option<&str> {
        match self {
            DefaultVal::Bool(_) => None,
            DefaultVal::Str(s) => Some(s.as_str()),
        }
    }
}

/// One toggleable feature in the manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeatureSpec {
    /// Cargo feature name (must match a real `[features]` entry in nemesisbot).
    pub id: String,
    /// Human-readable label shown in the TUI.
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub desc: String,
    /// Grouping for the menu (channels / subsystems / core / build).
    #[serde(default)]
    pub category: String,
    /// `"enum"` for multi-choice features; absent/empty => boolean on/off.
    #[serde(default, rename = "type")]
    pub feature_type: Option<String>,
    #[serde(default)]
    pub default: DefaultVal,
    /// Allowed values for enum features.
    #[serde(default)]
    pub options: Vec<String>,
    #[serde(default)]
    pub depends: Vec<String>,
    #[serde(default)]
    pub conflicts: Vec<String>,
}

impl FeatureSpec {
    pub fn is_enum(&self) -> bool {
        self.feature_type.as_deref() == Some("enum")
    }
}

/// The whole manifest = a list of `[[feature]]` entries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FeatureManifest {
    #[serde(default, rename = "feature")]
    pub features: Vec<FeatureSpec>,
}

impl FeatureManifest {
    pub fn parse(text: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(text)
    }

    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("read manifest {}: {}", path.display(), e))?;
        Self::parse(&text).map_err(|e| anyhow::anyhow!("parse manifest {}: {}", path.display(), e))
    }

    pub fn to_string(&self) -> Result<String, toml::ser::Error> {
        toml::to_string_pretty(self)
    }

    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let body =
            "# NemesisBot feature manifest. Hand-curated or generated by `nemesis-config init`.\n\
             # Single source of truth for the build configurator.\n\n"
                .to_string();
        let features = self.to_string()?;
        std::fs::write(path, body + &features)
            .map_err(|e| anyhow::anyhow!("write manifest {}: {}", path.display(), e))
    }

    /// All feature ids referenced anywhere (own id + depends + conflicts).
    pub fn all_ids(&self) -> BTreeSet<String> {
        let mut s = BTreeSet::new();
        for f in &self.features {
            s.insert(f.id.clone());
            for d in &f.depends {
                s.insert(d.clone());
            }
            for c in &f.conflicts {
                s.insert(c.clone());
            }
        }
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
[[feature]]
id = "channels-web"
label = "Web 通道"
desc = "内置 Web 界面"
category = "channels"
default = true

[[feature]]
id = "migrate"
label = "OpenClaw 迁移"
category = "subsystems"
default = true

[[feature]]
id = "build-profile"
label = "构建 profile"
category = "build"
type = "enum"
default = "release"
options = ["release", "iotsmall"]
"#;

    #[test]
    fn parses_sample_manifest() {
        let m = FeatureManifest::parse(SAMPLE).unwrap();
        assert_eq!(m.features.len(), 3);
        assert_eq!(m.features[0].id, "channels-web");
        assert_eq!(m.features[0].default.as_bool(), Some(true));
        assert!(!m.features[0].is_enum());
    }

    #[test]
    fn enum_feature_detected() {
        let m = FeatureManifest::parse(SAMPLE).unwrap();
        let bf = m.features.iter().find(|f| f.id == "build-profile").unwrap();
        assert!(bf.is_enum());
        assert_eq!(bf.default.as_str(), Some("release"));
        assert_eq!(
            bf.options,
            vec!["release".to_string(), "iotsmall".to_string()]
        );
    }

    #[test]
    fn roundtrip_preserves_features() {
        let m = FeatureManifest::parse(SAMPLE).unwrap();
        let text = m.to_string().unwrap();
        let m2 = FeatureManifest::parse(&text).unwrap();
        assert_eq!(m.features.len(), m2.features.len());
        assert_eq!(m2.features[0].id, "channels-web");
    }

    #[test]
    fn all_ids_collects_dependencies() {
        let text = r#"
[[feature]]
id = "a"
default = true
depends = ["b"]
[[feature]]
id = "b"
default = false
"#;
        let m = FeatureManifest::parse(text).unwrap();
        let ids = m.all_ids();
        assert!(ids.contains("a"));
        assert!(ids.contains("b"));
    }
}
