//! plugin-ui — NemesisBot pure UI plugin DLL
//!
//! Provides C ABI exports for creating WebView2 windows.
//! This DLL contains **zero business logic** — it only handles:
//! - Window creation and lifecycle
//! - WebView2 rendering
//! - User input capture (approval result)
//!
//! All content (HTML, URLs, init scripts) is provided by the host process.
//!
//! Build: `cargo build --release` → plugin-ui.dll
//! Place alongside nemesisbot.exe in plugins/ subdirectory.

mod host_services;

#[cfg(not(target_os = "linux"))]
mod window;

#[cfg(target_os = "linux")]
mod window_gtk;

#[cfg(target_os = "linux")]
mod appindicator_glib;

#[cfg(target_os = "linux")]
mod tray;

use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::sync::atomic::{AtomicBool, AtomicIsize, AtomicPtr, Ordering};
use std::sync::Mutex;

use host_services::HostServices;

/// DLL version string.
const PLUGIN_VERSION: &str = "0.2.0";

/// Global close-request flag. Set by `plugin_request_close()`,
/// checked by the event loop in `plugin_create_window()`.
static CLOSE_REQUESTED: AtomicBool = AtomicBool::new(false);

/// Global bring-to-front request flag. Set by `plugin_request_bring_to_front()`,
/// checked by the event loop to bring the window to the foreground.
static BRING_TO_FRONT_REQUESTED: AtomicBool = AtomicBool::new(false);

/// Global active window handle (HWND on Windows). Set after window creation.
/// Used by the event loop to call ShowWindow/SetForegroundWindow.
static ACTIVE_HWND: AtomicIsize = AtomicIsize::new(0);

/// Global approval result. Set by the approval window's custom protocol handler
/// when the user clicks Approve/Reject. Read by `plugin_get_approval_result()`.
/// Stored as CString for safe C ABI return (includes null terminator).
static APPROVAL_RESULT: Mutex<Option<CString>> = Mutex::new(None);

/// Stored host services pointer (set during plugin_init).
static HOST_PTR: AtomicPtr<HostServices> = AtomicPtr::new(std::ptr::null_mut());

/// Log a message via host services if available, otherwise eprintln.
fn log_msg(level: i32, msg: &str) {
    let host_ptr = HOST_PTR.load(Ordering::SeqCst);
    if !host_ptr.is_null() {
        let host = unsafe { &*host_ptr };
        host_services::host_log(Some(host), level, "plugin-ui", msg);
    } else {
        eprintln!("[plugin-ui] {}", msg);
    }
}

// ---------------------------------------------------------------------------
// Configuration types — pure window config, no business logic
// ---------------------------------------------------------------------------

/// Configuration passed from the host process via JSON.
///
/// This is a **pure window configuration** — all content (HTML, URLs, scripts)
/// is generated by the host process. The DLL does not interpret or generate
/// any business content.
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WindowConfig {
    /// Window type: "dashboard" or "approval".
    pub window_type: String,
    /// Window title.
    #[serde(default = "default_title")]
    pub title: String,
    /// Window width in pixels.
    #[serde(default = "default_width")]
    pub width: f64,
    /// Window height in pixels.
    #[serde(default = "default_height")]
    pub height: f64,
    /// URL to load in the WebView (dashboard windows).
    /// The host constructs the full URL including host:port.
    pub url: Option<String>,
    /// JavaScript initialization script injected before page load (dashboard windows).
    /// Used for token injection: `window.__DASHBOARD_TOKEN__="...";`
    pub init_script: Option<String>,
    /// HTML content to render (approval windows).
    /// The host generates the complete HTML page.
    pub html: Option<String>,
    /// Auto-close timeout in seconds for approval windows (safety net).
    /// Default: 120 seconds. The HTML JS countdown fires first; this is a fallback.
    #[serde(default = "default_timeout")]
    pub timeout_seconds: u64,
}

fn default_title() -> String { "NemesisBot".to_string() }
fn default_width() -> f64 { 1280.0 }
fn default_height() -> f64 { 800.0 }
fn default_timeout() -> u64 { 120 }

// ---------------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------------

/// Success.
pub const PLUGIN_OK: i32 = 0;
/// Failed to parse config JSON.
pub const PLUGIN_ERR_CONFIG: i32 = 1;
/// WebView2 runtime not available.
pub const PLUGIN_ERR_WEBVIEW2: i32 = 2;
/// Failed to create window.
pub const PLUGIN_ERR_WINDOW: i32 = 3;
/// Unknown window type.
pub const PLUGIN_ERR_UNKNOWN_TYPE: i32 = 5;

// ---------------------------------------------------------------------------
// C ABI exports — Unified Plugin Interface
// ---------------------------------------------------------------------------

/// Initialize the plugin.
///
/// `config_dir`: Directory path where plugin configuration files are located.
/// `host`: Pointer to HostServices vtable (may be NULL for standalone testing).
///
/// Returns: 0 on success, negative error code on failure.
#[no_mangle]
pub extern "C" fn plugin_init(config_dir: *const c_char, host: *const HostServices) -> i32 {
    // Store host pointer
    HOST_PTR.store(host as *mut HostServices, Ordering::SeqCst);

    if !config_dir.is_null() {
        let dir = unsafe { CStr::from_ptr(config_dir) }.to_string_lossy();
        log_msg(1, &format!("plugin_init: config_dir={}", dir));
    }

    // Check WebView2 availability
    if plugin_check_available() != 1 {
        log_msg(3, "plugin_init: WebView2 not available");
        // Not a fatal error — still return OK, window creation will fail later
    }

    log_msg(2, &format!("plugin_init: version={}, host={}", PLUGIN_VERSION, if host.is_null() { "none" } else { "provided" }));
    PLUGIN_OK
}

/// Release resources held by the plugin.
///
/// Idempotent — safe to call multiple times.
#[no_mangle]
pub extern "C" fn plugin_free() {
    HOST_PTR.store(std::ptr::null_mut(), Ordering::SeqCst);
    log_msg(2, "plugin_free: resources released");
}

// ---------------------------------------------------------------------------
// C ABI exports — Window management
// ---------------------------------------------------------------------------

/// Check if the plugin is available (WebView2 runtime installed on Windows).
///
/// Returns: 1 = available, 0 = not available.
#[no_mangle]
pub extern "C" fn plugin_check_available() -> i32 {
    #[cfg(target_os = "windows")]
    {
        use std::path::PathBuf;
        let local_app_data = std::env::var("LOCALAPPDATA").unwrap_or_default();
        let webview2_path = PathBuf::from(&local_app_data)
            .join("Microsoft")
            .join("EdgeWebView")
            .join("Application");
        let pf = std::env::var("ProgramFiles(x86)").unwrap_or_default();
        let system_webview2 = PathBuf::from(&pf)
            .join("Microsoft")
            .join("EdgeWebView")
            .join("Application");
        if webview2_path.exists() || system_webview2.exists() {
            1
        } else {
            1 // Fallback: assume available on modern Windows
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        1
    }
}

/// Get the plugin version as a C string pointer.
///
/// The returned pointer is valid for the lifetime of the DLL.
#[no_mangle]
pub extern "C" fn plugin_get_version() -> *const c_char {
    static VERSION: std::sync::OnceLock<CString> = std::sync::OnceLock::new();
    let cstr = VERSION.get_or_init(|| CString::new(PLUGIN_VERSION).unwrap());
    cstr.as_ptr()
}

/// Create and run a window (blocking call).
///
/// `config_json`: Null-terminated UTF-8 JSON string with WindowConfig fields.
///
/// Returns: 0 on success (window closed normally), non-zero error code on failure.
///
/// This function blocks until the window is closed or `plugin_request_close()` is called.
#[no_mangle]
pub extern "C" fn plugin_create_window(config_json: *const c_char) -> i32 {
    // Reset close flag for this invocation
    CLOSE_REQUESTED.store(false, Ordering::SeqCst);

    // Clear any previous approval result
    {
        let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
        *guard = None;
    }

    // Parse config JSON
    let config = match parse_config(config_json) {
        Ok(c) => c,
        Err(code) => return code,
    };

    // Dispatch to appropriate window handler
    let result = match config.window_type.as_str() {
        "dashboard" => {
            #[cfg(not(target_os = "linux"))]
            { window::create_dashboard_window(&config) }
            #[cfg(target_os = "linux")]
            { window_gtk::create_dashboard_window(&config) }
        }
        "approval" => {
            #[cfg(not(target_os = "linux"))]
            { window::create_approval_window(&config) }
            #[cfg(target_os = "linux")]
            { window_gtk::create_approval_window(&config) }
        }
        _ => {
            eprintln!("[plugin-ui] Unknown window type: {}", config.window_type);
            Err(PLUGIN_ERR_UNKNOWN_TYPE)
        }
    };

    match result {
        Ok(()) => PLUGIN_OK,
        Err(code) => code,
    }
}

/// Request the window to close.
///
/// Can be called from any thread. The event loop in `plugin_create_window()`
/// will detect this flag and close the window.
#[no_mangle]
pub extern "C" fn plugin_request_close() {
    CLOSE_REQUESTED.store(true, Ordering::SeqCst);
}

/// Request the window to be brought to the foreground.
///
/// Can be called from any thread (typically from the WebSocket notification
/// handler when the parent wants to deduplicate windows).
#[no_mangle]
pub extern "C" fn plugin_request_bring_to_front() {
    bring_window_to_foreground();
}

/// Get the approval result as a C string pointer.
///
/// Returns a pointer to a null-terminated UTF-8 string (e.g. "approved" or
/// "rejected"), or null if no result is available (window closed without action).
///
/// The returned pointer is valid until the next call to `plugin_create_window()`.
#[no_mangle]
pub extern "C" fn plugin_get_approval_result() -> *const c_char {
    let guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
    match guard.as_ref() {
        Some(cstr) => cstr.as_ptr(),
        None => std::ptr::null(),
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Parse a C string into a WindowConfig.
fn parse_config(ptr: *const c_char) -> Result<WindowConfig, i32> {
    if ptr.is_null() {
        eprintln!("[plugin-ui] config_json is null");
        return Err(PLUGIN_ERR_CONFIG);
    }

    let c_str = unsafe { CStr::from_ptr(ptr) };
    let json_str = match c_str.to_str() {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[plugin-ui] config is not valid UTF-8: {}", e);
            return Err(PLUGIN_ERR_CONFIG);
        }
    };

    match serde_json::from_str::<WindowConfig>(json_str) {
        Ok(config) => Ok(config),
        Err(e) => {
            eprintln!("[plugin-ui] failed to parse config JSON: {}", e);
            Err(PLUGIN_ERR_CONFIG)
        }
    }
}

/// Check if close has been requested (called from event loop).
pub fn is_close_requested() -> bool {
    CLOSE_REQUESTED.load(Ordering::SeqCst)
}

/// Check if bring-to-front has been requested, and clear the flag.
pub fn take_bring_to_front_requested() -> bool {
    BRING_TO_FRONT_REQUESTED.swap(false, Ordering::SeqCst)
}

/// Set the active window handle (HWND on Windows). Called after window creation.
pub fn set_active_hwnd(hwnd: isize) {
    ACTIVE_HWND.store(hwnd, Ordering::SeqCst);
}

/// Get the active window handle. Returns 0 if no window is active.
pub fn get_active_hwnd() -> isize {
    ACTIVE_HWND.load(Ordering::SeqCst)
}

/// Bring the window to the foreground using Win32 APIs.
pub fn bring_window_to_foreground() {
    let hwnd = get_active_hwnd();
    if hwnd == 0 {
        return;
    }

    #[cfg(target_os = "windows")]
    {
        // SW_RESTORE = 9
        unsafe {
            ShowWindow(hwnd, 9);
            SetForegroundWindow(hwnd);
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        let _ = hwnd;
    }
}

// Win32 FFI declarations (no windows-rs crate needed)
#[cfg(target_os = "windows")]
extern "system" {
    fn ShowWindow(hwnd: isize, ncmdshow: i32) -> i32;
    fn SetForegroundWindow(hwnd: isize) -> i32;
}

/// Store the approval result (called from the custom protocol handler).
///
/// Also sets the `CLOSE_REQUESTED` flag and posts `WM_CLOSE` to the window
/// so the event loop exits.
pub fn set_approval_result(result: &str) {
    let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
    *guard = Some(CString::new(result).unwrap_or_else(|_| CString::new("rejected").unwrap()));
    drop(guard);

    // Set flag — event loop checks this every 100ms via WaitUntil
    CLOSE_REQUESTED.store(true, Ordering::SeqCst);

    // Also post WM_CLOSE as a secondary mechanism to wake the event loop
    #[cfg(target_os = "windows")]
    {
        let hwnd = get_active_hwnd();
        if hwnd != 0 {
            // WM_CLOSE = 0x0010
            unsafe { PostMessageW(hwnd, 0x0010, 0, 0); }
        }
    }
}

// Additional Win32 FFI for PostMessageW
#[cfg(target_os = "windows")]
extern "system" {
    fn PostMessageW(hwnd: isize, msg: u32, wparam: usize, lparam: isize) -> i32;
}

/// Get the approval result as a Rust String (for testing).
pub fn get_approval_result_value() -> Option<String> {
    APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner())
        .as_ref()
        .map(|c| c.to_str().unwrap_or("rejected").to_string())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests;
