//! plugin-ui — NemesisBot pure UI plugin DLL
//!
//! Provides C ABI exports for creating WebView2 windows.
//! This DLL contains **zero business logic** — it only handles:
//! - Window creation and lifecycle
//! - WebView2 rendering
//! - User input capture (approval result)
//!
//! All content (HTML, URLs, init scripts) is provided by the host process.
//!
//! Build: `cargo build --release` → plugin-ui.dll
//! Place alongside nemesisbot.exe in plugins/ subdirectory.

mod window;

use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::sync::atomic::{AtomicBool, AtomicIsize, Ordering};
use std::sync::Mutex;

/// DLL version string.
const PLUGIN_VERSION: &str = "0.2.0";

/// Global close-request flag. Set by `plugin_request_close()`,
/// checked by the event loop in `plugin_create_window()`.
static CLOSE_REQUESTED: AtomicBool = AtomicBool::new(false);

/// Global bring-to-front request flag. Set by `plugin_request_bring_to_front()`,
/// checked by the event loop to bring the window to the foreground.
static BRING_TO_FRONT_REQUESTED: AtomicBool = AtomicBool::new(false);

/// Global active window handle (HWND on Windows). Set after window creation.
/// Used by the event loop to call ShowWindow/SetForegroundWindow.
static ACTIVE_HWND: AtomicIsize = AtomicIsize::new(0);

/// Global approval result. Set by the approval window's custom protocol handler
/// when the user clicks Approve/Reject. Read by `plugin_get_approval_result()`.
/// Stored as CString for safe C ABI return (includes null terminator).
static APPROVAL_RESULT: Mutex<Option<CString>> = Mutex::new(None);

// ---------------------------------------------------------------------------
// Configuration types — pure window config, no business logic
// ---------------------------------------------------------------------------

/// Configuration passed from the host process via JSON.
///
/// This is a **pure window configuration** — all content (HTML, URLs, scripts)
/// is generated by the host process. The DLL does not interpret or generate
/// any business content.
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WindowConfig {
    /// Window type: "dashboard" or "approval".
    pub window_type: String,
    /// Window title.
    #[serde(default = "default_title")]
    pub title: String,
    /// Window width in pixels.
    #[serde(default = "default_width")]
    pub width: f64,
    /// Window height in pixels.
    #[serde(default = "default_height")]
    pub height: f64,
    /// URL to load in the WebView (dashboard windows).
    /// The host constructs the full URL including host:port.
    pub url: Option<String>,
    /// JavaScript initialization script injected before page load (dashboard windows).
    /// Used for token injection: `window.__DASHBOARD_TOKEN__="...";`
    pub init_script: Option<String>,
    /// HTML content to render (approval windows).
    /// The host generates the complete HTML page.
    pub html: Option<String>,
    /// Auto-close timeout in seconds for approval windows (safety net).
    /// Default: 120 seconds. The HTML JS countdown fires first; this is a fallback.
    #[serde(default = "default_timeout")]
    pub timeout_seconds: u64,
}

fn default_title() -> String { "NemesisBot".to_string() }
fn default_width() -> f64 { 1280.0 }
fn default_height() -> f64 { 800.0 }
fn default_timeout() -> u64 { 120 }

// ---------------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------------

/// Success.
pub const PLUGIN_OK: i32 = 0;
/// Failed to parse config JSON.
pub const PLUGIN_ERR_CONFIG: i32 = 1;
/// WebView2 runtime not available.
pub const PLUGIN_ERR_WEBVIEW2: i32 = 2;
/// Failed to create window.
pub const PLUGIN_ERR_WINDOW: i32 = 3;
/// Unknown window type.
pub const PLUGIN_ERR_UNKNOWN_TYPE: i32 = 5;

// ---------------------------------------------------------------------------
// C ABI exports
// ---------------------------------------------------------------------------

/// Check if the plugin is available (WebView2 runtime installed on Windows).
///
/// Returns: 1 = available, 0 = not available.
#[no_mangle]
pub extern "C" fn plugin_check_available() -> i32 {
    #[cfg(target_os = "windows")]
    {
        use std::path::PathBuf;
        let local_app_data = std::env::var("LOCALAPPDATA").unwrap_or_default();
        let webview2_path = PathBuf::from(&local_app_data)
            .join("Microsoft")
            .join("EdgeWebView")
            .join("Application");
        let pf = std::env::var("ProgramFiles(x86)").unwrap_or_default();
        let system_webview2 = PathBuf::from(&pf)
            .join("Microsoft")
            .join("EdgeWebView")
            .join("Application");
        if webview2_path.exists() || system_webview2.exists() {
            1
        } else {
            1 // Fallback: assume available on modern Windows
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        1
    }
}

/// Get the plugin version as a C string pointer.
///
/// The returned pointer is valid for the lifetime of the DLL.
#[no_mangle]
pub extern "C" fn plugin_get_version() -> *const c_char {
    static VERSION: std::sync::OnceLock<CString> = std::sync::OnceLock::new();
    let cstr = VERSION.get_or_init(|| CString::new(PLUGIN_VERSION).unwrap());
    cstr.as_ptr()
}

/// Create and run a window (blocking call).
///
/// `config_json`: Null-terminated UTF-8 JSON string with WindowConfig fields.
///
/// Returns: 0 on success (window closed normally), non-zero error code on failure.
///
/// This function blocks until the window is closed or `plugin_request_close()` is called.
#[no_mangle]
pub extern "C" fn plugin_create_window(config_json: *const c_char) -> i32 {
    // Reset close flag for this invocation
    CLOSE_REQUESTED.store(false, Ordering::SeqCst);

    // Clear any previous approval result
    {
        let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
        *guard = None;
    }

    // Parse config JSON
    let config = match parse_config(config_json) {
        Ok(c) => c,
        Err(code) => return code,
    };

    // Dispatch to appropriate window handler
    let result = match config.window_type.as_str() {
        "dashboard" => window::create_dashboard_window(&config),
        "approval" => window::create_approval_window(&config),
        _ => {
            eprintln!("[plugin-ui] Unknown window type: {}", config.window_type);
            Err(PLUGIN_ERR_UNKNOWN_TYPE)
        }
    };

    match result {
        Ok(()) => PLUGIN_OK,
        Err(code) => code,
    }
}

/// Request the window to close.
///
/// Can be called from any thread. The event loop in `plugin_create_window()`
/// will detect this flag and close the window.
#[no_mangle]
pub extern "C" fn plugin_request_close() {
    CLOSE_REQUESTED.store(true, Ordering::SeqCst);
}

/// Request the window to be brought to the foreground.
///
/// Can be called from any thread (typically from the WebSocket notification
/// handler when the parent wants to deduplicate windows).
#[no_mangle]
pub extern "C" fn plugin_request_bring_to_front() {
    bring_window_to_foreground();
}

/// Get the approval result as a C string pointer.
///
/// Returns a pointer to a null-terminated UTF-8 string (e.g. "approved" or
/// "rejected"), or null if no result is available (window closed without action).
///
/// The returned pointer is valid until the next call to `plugin_create_window()`.
#[no_mangle]
pub extern "C" fn plugin_get_approval_result() -> *const c_char {
    let guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
    match guard.as_ref() {
        Some(cstr) => cstr.as_ptr(),
        None => std::ptr::null(),
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Parse a C string into a WindowConfig.
fn parse_config(ptr: *const c_char) -> Result<WindowConfig, i32> {
    if ptr.is_null() {
        eprintln!("[plugin-ui] config_json is null");
        return Err(PLUGIN_ERR_CONFIG);
    }

    let c_str = unsafe { CStr::from_ptr(ptr) };
    let json_str = match c_str.to_str() {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[plugin-ui] config is not valid UTF-8: {}", e);
            return Err(PLUGIN_ERR_CONFIG);
        }
    };

    match serde_json::from_str::<WindowConfig>(json_str) {
        Ok(config) => Ok(config),
        Err(e) => {
            eprintln!("[plugin-ui] failed to parse config JSON: {}", e);
            Err(PLUGIN_ERR_CONFIG)
        }
    }
}

/// Check if close has been requested (called from event loop).
pub fn is_close_requested() -> bool {
    CLOSE_REQUESTED.load(Ordering::SeqCst)
}

/// Check if bring-to-front has been requested, and clear the flag.
pub fn take_bring_to_front_requested() -> bool {
    BRING_TO_FRONT_REQUESTED.swap(false, Ordering::SeqCst)
}

/// Set the active window handle (HWND on Windows). Called after window creation.
pub fn set_active_hwnd(hwnd: isize) {
    ACTIVE_HWND.store(hwnd, Ordering::SeqCst);
}

/// Get the active window handle. Returns 0 if no window is active.
pub fn get_active_hwnd() -> isize {
    ACTIVE_HWND.load(Ordering::SeqCst)
}

/// Bring the window to the foreground using Win32 APIs.
pub fn bring_window_to_foreground() {
    let hwnd = get_active_hwnd();
    if hwnd == 0 {
        return;
    }

    #[cfg(target_os = "windows")]
    {
        // SW_RESTORE = 9
        unsafe {
            ShowWindow(hwnd, 9);
            SetForegroundWindow(hwnd);
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        let _ = hwnd;
    }
}

// Win32 FFI declarations (no windows-rs crate needed)
#[cfg(target_os = "windows")]
extern "system" {
    fn ShowWindow(hwnd: isize, ncmdshow: i32) -> i32;
    fn SetForegroundWindow(hwnd: isize) -> i32;
}

/// Store the approval result (called from the custom protocol handler).
///
/// Also sets the `CLOSE_REQUESTED` flag and posts `WM_CLOSE` to the window
/// so the event loop exits.
pub fn set_approval_result(result: &str) {
    let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
    *guard = Some(CString::new(result).unwrap_or_else(|_| CString::new("rejected").unwrap()));
    drop(guard);

    // Set flag — event loop checks this every 100ms via WaitUntil
    CLOSE_REQUESTED.store(true, Ordering::SeqCst);

    // Also post WM_CLOSE as a secondary mechanism to wake the event loop
    let hwnd = get_active_hwnd();
    if hwnd != 0 {
        // WM_CLOSE = 0x0010
        unsafe { PostMessageW(hwnd, 0x0010, 0, 0); }
    }
}

// Additional Win32 FFI for PostMessageW
#[cfg(target_os = "windows")]
extern "system" {
    fn PostMessageW(hwnd: isize, msg: u32, wparam: usize, lparam: isize) -> i32;
}

/// Get the approval result as a Rust String (for testing).
pub fn get_approval_result_value() -> Option<String> {
    APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner())
        .as_ref()
        .map(|c| c.to_str().unwrap_or("rejected").to_string())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn c_str(s: &str) -> *const c_char {
        CString::new(s).unwrap().into_raw() as *const _
    }

    #[test]
    fn test_plugin_check_available() {
        let result = plugin_check_available();
        assert_eq!(result, 1);
    }

    #[test]
    fn test_plugin_get_version() {
        let ptr = plugin_get_version();
        assert!(!ptr.is_null());
        let version = unsafe { CStr::from_ptr(ptr) }.to_str().unwrap();
        assert_eq!(version, "0.2.0");
    }

    #[test]
    fn test_parse_config_null() {
        let result = parse_config(std::ptr::null());
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), PLUGIN_ERR_CONFIG);
    }

    #[test]
    fn test_parse_config_invalid_json() {
        let ptr = c_str("not json");
        let result = parse_config(ptr);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), PLUGIN_ERR_CONFIG);
    }

    #[test]
    fn test_parse_config_valid_dashboard() {
        let json = r#"{"window_type":"dashboard","title":"Test","width":800,"height":600,"url":"http://127.0.0.1:49000/","init_script":"window.__DASHBOARD_TOKEN__=\"abc123\";"}"#;
        let ptr = c_str(json);
        let config = parse_config(ptr).unwrap();
        assert_eq!(config.window_type, "dashboard");
        assert_eq!(config.title, "Test");
        assert_eq!(config.width, 800.0);
        assert_eq!(config.height, 600.0);
        assert_eq!(config.url.as_deref(), Some("http://127.0.0.1:49000/"));
        assert_eq!(config.init_script.as_deref(), Some("window.__DASHBOARD_TOKEN__=\"abc123\";"));
        assert!(config.html.is_none());
    }

    #[test]
    fn test_parse_config_valid_approval() {
        let json = r#"{"window_type":"approval","title":"Approval","html":"<html><body>Approve?</body></html>","timeout_seconds":60}"#;
        let ptr = c_str(json);
        let config = parse_config(ptr).unwrap();
        assert_eq!(config.window_type, "approval");
        assert_eq!(config.html.as_deref(), Some("<html><body>Approve?</body></html>"));
        assert_eq!(config.timeout_seconds, 60);
        assert!(config.url.is_none());
    }

    #[test]
    fn test_parse_config_defaults() {
        let json = r#"{"window_type":"dashboard"}"#;
        let ptr = c_str(json);
        let config = parse_config(ptr).unwrap();
        assert_eq!(config.title, "NemesisBot");
        assert_eq!(config.width, 1280.0);
        assert_eq!(config.height, 800.0);
        assert_eq!(config.timeout_seconds, 120);
    }

    #[test]
    fn test_close_request_flag() {
        CLOSE_REQUESTED.store(false, Ordering::SeqCst);
        assert!(!is_close_requested());
        plugin_request_close();
        assert!(is_close_requested());
        CLOSE_REQUESTED.store(false, Ordering::SeqCst);
    }

    #[test]
    fn test_bring_to_front_flag() {
        BRING_TO_FRONT_REQUESTED.store(false, Ordering::SeqCst);
        assert!(!take_bring_to_front_requested());

        BRING_TO_FRONT_REQUESTED.store(true, Ordering::SeqCst);
        assert!(take_bring_to_front_requested());
        assert!(!take_bring_to_front_requested());
    }

    #[test]
    fn test_active_hwnd() {
        set_active_hwnd(0);
        assert_eq!(get_active_hwnd(), 0);
        set_active_hwnd(12345);
        assert_eq!(get_active_hwnd(), 12345);
        set_active_hwnd(0);
    }

    #[test]
    fn test_bring_to_foreground_no_hwnd() {
        set_active_hwnd(0);
        bring_window_to_foreground();
    }

    #[test]
    fn test_approval_result_set_and_get() {
        {
            let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
            *guard = None;
        }
        assert!(get_approval_result_value().is_none());

        set_approval_result("approved");
        assert_eq!(get_approval_result_value().as_deref(), Some("approved"));

        let ptr = plugin_get_approval_result();
        assert!(!ptr.is_null());
        let s = unsafe { CStr::from_ptr(ptr) }.to_str().unwrap();
        assert_eq!(s, "approved");

        {
            let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
            *guard = None;
        }
        assert!(get_approval_result_value().is_none());
    }

    #[test]
    fn test_approval_result_null_when_empty() {
        {
            let mut guard = APPROVAL_RESULT.lock().unwrap_or_else(|e| e.into_inner());
            *guard = None;
        }
        let ptr = plugin_get_approval_result();
        assert!(ptr.is_null());
    }

    #[test]
    fn test_error_codes() {
        assert_eq!(PLUGIN_OK, 0);
        assert_eq!(PLUGIN_ERR_CONFIG, 1);
        assert_eq!(PLUGIN_ERR_WEBVIEW2, 2);
        assert_eq!(PLUGIN_ERR_WINDOW, 3);
        assert_eq!(PLUGIN_ERR_UNKNOWN_TYPE, 5);
    }

    #[test]
    fn test_window_config_missing_optional_fields() {
        let json = r#"{"window_type":"dashboard"}"#;
        let config: WindowConfig = serde_json::from_str(json).unwrap();
        assert!(config.url.is_none());
        assert!(config.init_script.is_none());
        assert!(config.html.is_none());
        assert_eq!(config.timeout_seconds, 120);
    }
}
