use super::*;
use crate::collector::Collector;
use crate::types::CollectedExperience;
use async_trait::async_trait;
use nemesis_types::forge::Experience;

/// A mock LLM caller that returns a generated skill/script content.
struct MockLLMCaller;

#[async_trait]
impl LLMCaller for MockLLMCaller {
    async fn chat(
        &self,
        _system_prompt: &str,
        _user_prompt: &str,
        _max_tokens: Option<i64>,
    ) -> Result<String, String> {
        Ok("---\nname: mock-skill\ndescription: Mock generated content\n---\n\n# Mock Skill\n\nGenerated by mock LLM.".to_string())
    }
}

fn make_collected(tool: &str, input: &str, success: bool) -> CollectedExperience {
    let hash = Collector::dedup_hash(tool, &serde_json::json!({"input": input}));
    let exp = Experience {
        id: uuid::Uuid::new_v4().to_string(),
        tool_name: tool.into(),
        input_summary: input.into(),
        output_summary: if success { "ok".into() } else { "err".into() },
        success,
        duration_ms: 100,
        timestamp: "2026-04-29T00:00:00Z".into(),
        session_key: "sess-test".into(),
    };
    CollectedExperience {
        experience: exp,
        dedup_hash: hash,
    }
}

#[tokio::test]
async fn test_create_skill_template() {
    let factory = Factory::new();
    let experiences = vec![
        make_collected("file_read", "read config", true),
        make_collected("file_write", "write result", true),
    ];
    let artifact = factory.create_skill("config-handler", &experiences).await;
    assert_eq!(artifact.name, "config-handler");
    assert_eq!(artifact.kind, ArtifactKind::Skill);
    assert_eq!(artifact.status, ArtifactStatus::Draft);
    assert!(!artifact.tool_signature.is_empty());
    assert!(artifact.content.contains("config-handler"));
}

#[tokio::test]
async fn test_create_skill_with_llm() {
    let factory = Factory::with_llm(Box::new(MockLLMCaller));
    let experiences = vec![
        make_collected("file_read", "read config", true),
        make_collected("file_write", "write result", true),
    ];
    let artifact = factory.create_skill("config-handler", &experiences).await;
    assert_eq!(artifact.name, "config-handler");
    assert_eq!(artifact.kind, ArtifactKind::Skill);
    // LLM-generated content should be present (or template fallback)
    assert!(!artifact.content.is_empty());
}

#[tokio::test]
async fn test_create_script_template() {
    let factory = Factory::new();
    let experiences = vec![make_collected("shell_exec", "run deploy", true)];
    let artifact = factory.create_script("deploy-script", &experiences).await;
    assert_eq!(artifact.name, "deploy-script");
    assert_eq!(artifact.kind, ArtifactKind::Script);
    assert!(artifact.content.contains("#!/usr/bin/env bash"));
}

#[tokio::test]
async fn test_create_script_with_llm() {
    let factory = Factory::with_llm(Box::new(MockLLMCaller));
    let experiences = vec![make_collected("shell_exec", "run deploy", true)];
    let artifact = factory.create_script("deploy-script", &experiences).await;
    assert_eq!(artifact.name, "deploy-script");
    assert_eq!(artifact.kind, ArtifactKind::Script);
    assert!(!artifact.content.is_empty());
}

#[test]
fn test_evaluate_artifact() {
    let factory = Factory::new();
    let experiences = vec![make_collected("file_read", "a.txt", true)];
    let rt = tokio::runtime::Runtime::new().unwrap();
    let artifact = rt.block_on(factory.create_skill("test-skill", &experiences));
    let eval = factory.evaluate_artifact(&artifact);

    assert!(eval.quality_score > 0.0);
    // Template content should have "description", "usage", "example"
    assert!(
        eval.quality_score >= 0.6,
        "score was {}",
        eval.quality_score
    );
}
