/// <reference types="vite/client" />

// Feature-gating env vars generated by `nemesis-build-config export
// --frontend-env` (from scripts/customize/.config). Absent (full build) =>
// undefined, which the router/sidebar treat as "feature on" via `!== 'false'`.
interface ImportMetaEnv {
  readonly [key: `VITE_FEATURE_${string}`]: string | undefined
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}
