//! S12b batch tests (quality-hardening goal 冲刺)：`main` 的启动路径
//! `run()` 抽出后整体可达——--init-keys 密钥生成 + AppState 组装 + 路由装配 +
//! bind/serve 用「探测空闲口 → --bind 127.0.0.1:<probe>」技巧在临时目录实测。
//! 只绑 127.0.0.1 的 OS 分配端口（绝不占项目保留口 18790/49000/49001/8080）。
//!
//! 仍属结构性不可达、不在本批硬追的部分：真实 argv 解析进 `main()` 本体
//! （clap 已有专项测试），以及长驻 serve 循环的优雅退出臂（abort 收尾）。

use super::*;
use nemesis_verify::keygen::KeyHierarchy;
use std::sync::atomic::{AtomicU32, Ordering};
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};

static SEQ: AtomicU32 = AtomicU32::new(0);

/// 唯一临时文件路径（pid + 序号防并行冲突；仓库既有范式，见 state/tests.rs）。
fn temp_path(tag: &str, ext: &str) -> String {
    let n = SEQ.fetch_add(1, Ordering::SeqCst);
    std::env::temp_dir()
        .join(format!(
            "revoke_s12b_{tag}_{}_{}{ext}",
            std::process::id(),
            n
        ))
        .to_string_lossy()
        .into_owned()
}

/// 探测一个 OS 分配的空闲回环端口后立即释放。探测→复用存在微小 TOCTOU 窗口，
/// 单进程测试内可接受（规格许可的「TcpListener 探测空闲口 → --bind」技巧）。
fn free_loopback_port() -> u16 {
    std::net::TcpListener::bind("127.0.0.1:0")
        .expect("probe bind 127.0.0.1:0")
        .local_addr()
        .expect("probe local_addr")
        .port()
}

/// 裸 TCP 发一个 HTTP/1.1 GET 并读完整响应（零新增依赖；Connection: close）。
async fn http_get(port: u16, path: &str) -> Option<String> {
    let mut stream = tokio::net::TcpStream::connect(("127.0.0.1", port))
        .await
        .ok()?;
    let req = format!("GET {path} HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n");
    stream.write_all(req.as_bytes()).await.ok()?;
    let mut buf = Vec::new();
    stream.read_to_end(&mut buf).await.ok()?;
    Some(String::from_utf8_lossy(&buf).into_owned())
}

#[tokio::test(flavor = "multi_thread")]
async fn run_boots_full_server_and_init_keys_on_ephemeral_port() {
    let keys = temp_path("boot", ".json");
    let db = temp_path("boot", ".db");
    let _ = std::fs::remove_file(&keys);
    let _ = std::fs::remove_file(&db);
    let port = free_loopback_port();
    let cli = Cli {
        bind: format!("127.0.0.1:{port}"),
        db_url: db.clone(),
        keys_file: keys.clone(),
        init_keys: true,
        admin_token: "s12b-tok".to_string(),
    };
    // init_keys=true → run() 先生成密钥体系，再组装 AppState/Router 并起服务
    let server = tokio::spawn(run(cli));

    // 轮询 /v1/health 直到就绪（≤15s，防慢机 flake）
    let deadline = tokio::time::Instant::now() + Duration::from_secs(15);
    let mut health_ok = false;
    while tokio::time::Instant::now() < deadline {
        if let Some(resp) = http_get(port, "/v1/health").await
            && (resp.starts_with("HTTP/1.1 200") || resp.contains(" 200 "))
        {
            health_ok = true;
            break;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    assert!(health_ok, "server did not come up on port {port} in time");

    // init_keys 副作用落地：密钥文件可回读为合法密钥体系
    let h = KeyHierarchy::load(&keys).expect("keys file generated by run()");
    let _root_hex = nemesis_verify::hex_util::hex_encode(&h.root_vk.to_bytes());

    // 第二条路由确认装配完整：/v1/crl 返回根签 SignedResponse{payload: Crl}
    let crl_resp = http_get(port, "/v1/crl")
        .await
        .expect("crl endpoint reachable");
    assert!(crl_resp.contains(" 200 "), "crl resp: {crl_resp}");
    let body_start = crl_resp
        .find("\r\n\r\n")
        .map(|i| &crl_resp[i + 4..])
        .unwrap_or("");
    let v: serde_json::Value = serde_json::from_str(body_start.trim()).expect("crl JSON body");
    assert_eq!(v["payload"]["version"], 1, "初始 CRL version=1: {v}");
    assert!(!v["sig"].as_str().unwrap_or("").is_empty(), "带根签");

    server.abort();
    let _ = server.await; // join 确保 abort 后 future 全部 drop（Windows 释放 DB 文件锁）
    let _ = std::fs::remove_file(&db);
    let _ = std::fs::remove_file(&keys);
}

#[tokio::test]
async fn run_without_init_keys_and_missing_keyfile_is_err() {
    let keys = temp_path("nokeys", ".json");
    let db = temp_path("nokeys", ".db");
    let _ = std::fs::remove_file(&keys);
    let _ = std::fs::remove_file(&db);
    // 不触发网络：AppState 组装在 bind 之前就会因缺密钥文件失败
    let cli = Cli {
        bind: "127.0.0.1:0".to_string(),
        db_url: db,
        keys_file: keys.clone(),
        init_keys: false,
        admin_token: "t".to_string(),
    };
    let err = run(cli).await.unwrap_err().to_string();
    assert!(err.contains("load keys file"), "错误应来自密钥加载: {err}");
    let _ = std::fs::remove_file(&keys);
}
